### ISSUE TITLE
Improvement on case sensitive

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/go-input-autocomplete#10]
Like bash/cmd if you have a directory that starts with an uppercase letter and if you type it's name starting with a lowercase, the autocompletion handle the case sensitive. This program is not handling it, you need to type the uppercase letter in order to autocomplete.

**Comment by RascalTwo** [comment]
Hey, I can do this, may I be assigned?

***

Copying the native [`hasPrefix`](https://golang.org/pkg/strings/#HasPrefix) code and replacing the `==` equality with a call to [`EqualFold`](https://golang.org/pkg/strings/#EqualFold) works in all the tests I've done.

There also probably a [`regexp`](https://golang.org/pkg/regexp/) way to do it, but I'd wager that it'd be more error prone and slower then using a modified `hasPrefix`.

**Comment by JoaoDanielRufino** [comment]
> Hey, I can do this, may I be assigned?
> 
> Copying the native [`hasPrefix`](https://golang.org/pkg/strings/#HasPrefix) code and replacing the `==` equality with a call to [`EqualFold`](https://golang.org/pkg/strings/#EqualFold) works in all the tests I've done.
> 
> There also probably a [`regexp`](https://golang.org/pkg/regexp/) way to do it, but I'd wager that it'd be more error prone and slower then using a modified `hasPrefix`.

Sure, you can do it :)
