### ISSUE TITLE
Create Makefile

### ISSUE THREAD

**Issue by tzzed** [JoaoDanielRufino/go-input-autocomplete#16]
Having a `Makefile` will be very helpfull for use.

**Comment by JoaoDanielRufino** [comment]
> Having a `Makefile` will be very helpfull for use.

Can you explain how a `Makefile` would be helpful?

**Comment by WheeskyJack** [comment]
Hi,
What will be the intent/functionality of Makefile? Will it create a executable or run unit tests or both?
@JoaoDanielRufino @tzzed 
It will be helpful if this gets clarified. 
I would like to work on it...
Br.

**Comment by WheeskyJack** [comment]
Hi @JoaoDanielRufino ,
I have created PR for this. #26 
Please review and let me know.
Br.
