### ISSUE TITLE
[feature] allow up and down arrow keys to select perticular subdirectory for traversal 

### ISSUE THREAD

**Issue by WheeskyJack** [JoaoDanielRufino/go-input-autocomplete#28]
Hi @JoaoDanielRufino ,
currently autocomplete doesn't give flexibility of listing sub-directories of given directory. This may pose little inconvenience to user if she doesn't already know the name of sub-directory. So , proposal is along with tab key, we should support up/down arrow keys, which will display the sub-directories name one by one. This will help user in selecting particular sub-directory more easily.
What you say?
Regards.

**Comment by JoaoDanielRufino** [comment]
Hi @WheeskyJack, this is a really good idea, it will help a lot.
Thanks.
