### ISSUE TITLE
[issue] throw an error when ctrl+c and similar key sequences are pressed

### ISSUE THREAD

**Issue by WheeskyJack** [JoaoDanielRufino/go-input-autocomplete#31]
Hi,
currently , when ctrl+c is pressed, the interrupt signal is caught by autocomplete but no action is taken on it and is ignored.
Issue is to define the behavior of system when such key sequences are pressed and throw error if desired to parent functions.
Regards.

**Comment by JoaoDanielRufino** [comment]
Fixed!
