### ISSUE TITLE
Tab cycles through all possible suggestions

### ISSUE THREAD

**Issue by uruun** [JoaoDanielRufino/go-input-autocomplete#34]
To make it more user friendly tab should show or cycle through all possible suggestions to the provided path. Example:
I have a directory with files:
_test1_, _test2_
When I type _test_ and press tab it should show _test1_, when I press it again it should show _test2_, again and it should show _test1_ back again.

**Comment by JoaoDanielRufino** [comment]
Awesome feature! Thanks for the comment
