### ISSUE TITLE
[issue] Parse input spaces properly

### ISSUE THREAD

**Issue by uruun** [JoaoDanielRufino/go-input-autocomplete#35]
Tab autocomplete works with directories with spaces but only when spaces are not typed directly. Example:
On Windows I want to autocomplete "C:\Program Files\", I have to type "C:\Program" and press tab. When I type "C:\Program<**space**>F" and press tab, it won't autocomplete. Issue also exists on Linux.

**Comment by JoaoDanielRufino** [comment]
Thanks for the comment!
