### ISSUE TITLE
Clean code and good structure

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/go-input-autocomplete#4]
Any help with clean code and a better structure is wanted.

**Comment by tzzed** [comment]
What do you think about start message.
```bash
$>go run main.go
 welcome to input-autocomplete.
press quit or exit program.
Path: /home/enjoy
```

**Comment by JoaoDanielRufino** [comment]
> What do you think about start message.
> 
> ```shell
> $>go run main.go
>  welcome to input-autocomplete.
> press quit or exit program.
> Path: /home/enjoy
> ```

I don't think it is a good thing, because people are going to use this library inside their code and they don't want to see a start message, they only want the autocomplete functionality, like native bash/cmd.

**Comment by tzzed** [comment]
Yes but it can be used as a cli.
