### ISSUE TITLE
Improvement in general

### ISSUE THREAD

**Issue by JoaoDanielRufino** [JoaoDanielRufino/go-input-autocomplete#8]
Any improvement on the code will be accepted

**Comment by WheeskyJack** [comment]
Hi @JoaoDanielRufino ,
created pull request for this. please review 
https://github.com/JoaoDanielRufino/go-input-autocomplete/pull/24
Br.

**Comment by WheeskyJack** [comment]
Hi @JoaoDanielRufino ,
created pull request for this. please review
#25 
Br.
